# Generated by Django 2.0.2 on 2018-08-13 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('biography', models.TextField()),
                ('LinkedIn', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
